disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - fatal_error_message
  - first_where
  - implicit_return
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - .build
  - Packages
  - DerivedData

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
